apiVersion: v1
kind: Pod
metadata:
  name: gu-busybox-odd
  labels:
    app: busybox
spec:
  containers:
  - image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
    command:
      - sleep
      - "36000"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      requests:
        cpu: "1"
        memory: "1G"
      limits:
        cpu: "1"
        memory: "1G"
