apiVersion: v1
kind: Pod
metadata:
  name: gu-busybox-even
  labels:
    app: busybox
spec:
  containers:
  - image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
    command:
      - "/bin/sh"
      - "-c"
      - "grep Cpus_allowed_list /proc/self/status | cut -f2 && sleep 1d"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      requests:
        cpu: "2"
        memory: "1G"
      limits:
        cpu: "2"
        memory: "1G"
